language: minimal
services: docker

env:
  global:
    - FOO=BAR
  matrix:
    - ELM_VERSION=0.18.0
      ELM_TEST_VERSION=latest-0.18.0
      NODE_VERSION=7
    - ELM_VERSION=0.18.0
      ELM_TEST_VERSION=latest-0.18.0
      NODE_VERSION=15
    - ELM_VERSION=latest-0.19.1
      ELM_TEST_VERSION=latest-0.19.1
      NODE_VERSION=15

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - |
    docker build \
      --build-arg NODE_VERSION=$NODE_VERSION \
      --build-arg ELM_VERSION=$ELM_VERSION \
      -t rubyisbeautiful/elm-docker:$NODE_VERSION-$ELM_VERSION \
      .
  - docker push rubyisbeautiful/elm-docker:$NODE_VERSION-$ELM_VERSION
